[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.9"
dependencies = [
    "fastapi[standard]>=0.116.2",
    "google-generativeai>=0.8.0",
    "pydantic>=2.0.0",
]
